version: "3"
services:
  postgres:
    image: "postgres:16"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "postgres" ]
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    volumes:
      - /data/psql:/var/lib/postgresql/data
  go_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PSQL_HOST: "postgres"
      PSQL_PASSWORD: "mysecretpassword"
      WEB_HOST: "0.0.0.0"
    ports:
      - "8080:80"
    volumes:
      - static:/tmp/migration
    depends_on:
      - migration
  migration:
    image: "migrate/migrate:v4.16.0"
    volumes:
      - static:/migration
    command: ["-path=/migration", "-database=postgres://postgres:5432/postgres?sslmode=disable&user=postgres&password=mysecretpassword", "up"]
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  static: